### ISSUE TITLE
Are this counters correct? They always start with 0 of 1 and they never reach 1.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-visualization-toolkit#102]
![screen shot 2017-03-19 at 13 28 53](https://cloud.githubusercontent.com/assets/3181302/24081250/1cb464c8-0ca8-11e7-8b5f-0d770fb19a04.png)

**Comment by chalkos** [comment]
They are meant as "completed 0 out of a total of 1". They are counting the number of schemas processed.

In your screenshot there is only one schema, so when that schema is finished the whole database is finished and the database page is shown. That is why you never get to see "1 of 1".

**Comment by jmaferreira** [comment]
If the log is after the thing was done it should say 1 of 1.

**Comment by chalkos** [comment]
When the thing is done, the next thing immediately begins. So in reality you never get to see "1 of 1" of the current thing, you see the next thing's counter.

I could add code to smoothen that transition, which would always try to add the first and last pieces of a counter (eg. "0 of 3" and "3 of 3"). Is this what you intend by"

**Comment by jmaferreira** [comment]
I would prefer to see a list of 3 of 3s than a list of 0 of 3s… otherwise it seems as nothing is being done.

Meaning that, if you can’t report the entire sequence… 1 of 3, 2 of 3, and 3 of 3.. just report it on the end of the action (and not at the beginning).

**Comment by chalkos** [comment]
Ok. That seems like a good way to let the user know that stuff is getting done without being too verbose.

**Comment by chalkos** [comment]
The log shows (`completed+processing` of `total`) instead of (`completed` of `total`).

ie: 1st table is shown as (1 of X), 2nd table is shown as (2 of X), etc. to avoid showing (0 of X) and appearing to be doing nothing. Same goes for schemas:
![rsz_screenshot_from_2017-03-20_16-05-37](https://cloud.githubusercontent.com/assets/98429/24109083/82f6c610-0d87-11e7-99c7-e1c515c25eae.png)

The current table is always shown at 100% completion before moving on to the next table.
![rsz_screenshot_from_2017-03-20_16-06-03](https://cloud.githubusercontent.com/assets/98429/24109082/82ee87f2-0d87-11e7-8642-128e265a5fff.png)

If there is more than one schema, the current table on the current schema is shown at 100% before showing the line about the next schema.

I think this solves this issue, let me know if you have other suggestions.
