### ISSUE TITLE
Empty language/login menu make scroll when integrated with RODA

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#115]
![dbvtk_menu_scroll2](https://user-images.githubusercontent.com/631728/29404294-8f2eeb4e-8332-11e7-847a-46c7b1c3063a.png)

**Comment by hsilva-keep** [comment]
User menu, in nobranding mode, has been hidden (as requested by @jmaferreira). But what is the problem after all?

**Comment by chalkos** [comment]
@hsilva-keep the title is indeed a bit cryptic :upside_down_face: 
the horizontal scroll appears because the language&login menu is empty (when nobranding is used) and for some reason that makes it move a bit to the right. That is what is making the scroll appear.

Using `display:none` when nobranding is being used could be a solution for this (tried it in the browser inspector and it worked)

**Comment by chalkos** [comment]
@luis100 the iframe resizing library I added to DBVTK and RODA makes the `iframe` behave like a `div`, making the iframe expand to its contents full height and removing vertical scrollbars (and it probably also removed some padding or margin that was making the horizontal scrolling appear)
