### ISSUE TITLE
 Automatically translate codes in associative table resolving many-to-many relationships

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#150]
User needs exports of lists, where the codes are resolved. Automatically translate codes in associative table resolving many-many relations. Make a report and export this report.

---

Problem: Sometimes a code explanation is to be found among many columns in a table. Implement a function that allows the user to choose the preferred code explanation column/s for the export, if the explanation is found in a table with more than 2 columns. Otherwise do it automatically.

E.g. Export a list with names of all the movies Karen Jackson has rented (from the Sakila database).

---

Must manually define all many-to-many relationship tables.
Result may take a lot of time to calculate, must record the request and send response (e.g. via email) when done.
This will require use of advanced SOLR 7 features like streaming for map reduce or graph transversal.
https://lucene.apache.org/solr/guide/7_0/streaming-expressions.html

**Comment by luis100** [comment]
Requires #126

**Comment by 006627** [comment]
In order to improve the user experience in searching and viewing information, it was decided that this functionality should be the responsibility of the system administrator because it is necessary to have knowledge about the database in order to transform it in a detailed way.

This issue was divided into a few steps:

**Migration to Solr 8.3**
In order to use solr nested document for de-normalize tables of database, it was necessary set version of solr to 8.3
- Implementation 8243dd10a95f7bda7deb405989a0fdd7df9cbd43
[nested documents](https://lucene.apache.org/solr/guide/8_3/indexing-nested-documents.html)

**Configuration panel**
Added a configuration panel with the goal of improving the visualization and search of information in the database.
- Configuration main panel 84bb5e2344f41c7de2596d45dddbb1e7ef0aff3a
- Table management 6662fd6a5ef7a49d8477db439194b98217a83e83
- Column management 2f4bf3a967fb54e90ae31f49f7a90aba85fcefcc
- Data transformation configuration d6870fcde7564f9f68d05c4266cb998d64028408

**Spring Batch**
Use Spring Batch to process data transformation in parallel and in background.
- Implementation 0447d57b823943d43b036cc50b9958f33e1afd39
- Added job list panel 814782dcc51e1dda2e5cac80535d781034bd3d7e
- Added job info to SOLR 171f463d9eee631be9f20d65309bc5fd0d615ec3

**Data transformation**
This functionality allows to aggregate tables that are related and showing the information in a more human-readable format.
- Added panel fcb2e84762d0797147d898df148b93f53fa4ceb2 e3bc60cdeed3e17639ae875ace5762311a9d379d
- Added information to tableRowList de363e92039483dfc291865b3587998896120759
- Data transformation process 132b5e64c6c415bc100de05e5f5e7f6a50a487b5

Close at ed820889a9967d07dfd90576a8d2d51cc093f11b
