### ISSUE TITLE
"Saved searches" not a possibility in Entreprise og Desktop Version anymore

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#218]
In the menu to the left there is a "Saved searches"
Previously you could save searches but this seems not to be a function in Desktop 2.4.1 or Entreprise anymore? 

![image](https://user-images.githubusercontent.com/15984159/81927730-6d79c380-95e4-11ea-87b5-b282a192566a.png)

![image](https://user-images.githubusercontent.com/15984159/81927835-9c903500-95e4-11ea-8fa9-d31a4831cf0d.png)

**Comment by luis100** [comment]
Saved searches are there and work, but due to a change in the default behavior (#219), you need to activate advanced search in column configuration to get to that feature.

As administrator, go to a table and select CONFIGURATION > MANAGE TABLE, then select the advanced search checkbox on some columns.

![Captura de ecrã 2020-05-14, às 17 42 09](https://user-images.githubusercontent.com/631728/81961417-3f0edf00-960a-11ea-9784-ae5f104c1c4a.png)

Then go back to the table, and click  "advanced" and you'll find the SAVE SEARCH button.

![Captura de ecrã 2020-05-14, às 17 43 23](https://user-images.githubusercontent.com/631728/81961552-6cf42380-960a-11ea-898c-ac50b9dda285.png)

**Comment by PhillipTommerholt** [comment]
Thanks Luis!
