### ISSUE TITLE
Add visual clue about what is searched in "Search whole database"

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#47]
By @PhillipTommerholt:

> Could there be information on the "Search whole database" so it is explained to the user what the engine actually searches for (where it searches)?

**Comment by chalkos** [comment]
You mean in which tables and columns it searches?

Ideally it would search everything (may not be happening exactly like this though), so I don't see the need to show each table and column searched..

**Comment by PhillipTommerholt** [comment]
I am just thinking that the user would like to know what is meant by "search whole database".
Does the tool search in table data only? Or does it also search in metadata? 
What happens if a column is called "Employee_name" and I search for employee?

As it is now I only get results from table data, so it wouldn't come up.

**Comment by chalkos** [comment]
I see. It only searches data.

Maybe changing the page title would be better. To something like "Search all records" or "Search in all records"...

**Comment by PhillipTommerholt** [comment]
> Maybe changing the page title would be better. To something like "Search all records" or "Search in all records"...

Yes, I believe that would be more accurate and guiding.
