### ISSUE TITLE
when changing page, the browser should scroll to the top of the page

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#61]
Description: User is on page "Schema" (Sakila) and looks at the structure of database. Now user scrolls down to see table "staff". User clicks on the table name "staff". The table page "staff" is opened and it is scrolled to the bottom as the application somehow remembers the last position of the scrollbar (see picture attached).
When user is on the page "Schema" and clicks to the first item "actor" then the opened page "actor" is nicely at the beginning.

Browser
Chrome

![image](https://cloud.githubusercontent.com/assets/3479156/18263706/b359a5fa-7414-11e6-9c71-f79f56163533.png)

**Comment by chalkos** [comment]
If I scroll down until actor (on the left side) is very close to the top of the page and then click it, I get this:

<img width="1150" alt="screenshot of google chrome" src="https://cloud.githubusercontent.com/assets/98429/18276740/f421660c-7443-11e6-94fa-6b8dcb5fc011.png">

And in there the scroll does not appear in the beginning of the table. This happens because the application really does remember the scroll position and tries to keep it in the same place.

**Comment by Laurira** [comment]
Sorry but I don't understand if we are on the same page. I was talking about the situation where user is on page "http://demo.database-preservation.com/#schema/233ecc1a-2d06-44a0-abcc-6085105be618/a26b128e-1ccc-45bd-b892-12136d2a132b/structure" and now scrolls down and clicks on the table name "Store". Also please consider that the window size is smaller. Plese see the file below. It can be opened in a browser.
[scroll.zip](https://github.com/keeps/db-visualization-toolkit/files/458493/scroll.zip)

**Comment by chalkos** [comment]
I have a better understanding of the problem now, this is definitely something that should change.

What would you consider to be the correct behaviour? To scroll to the top of the page (or to the part of the page just below the header) every time the page changes?

**Comment by Laurira** [comment]
I think both options will be good. Maybe the schema->table should be shown as user can then easily understand where was he or she directed.
